### ISSUE TITLE
features

### ISSUE THREAD

**Issue by NoseyParker** [exploitagency/vanitygen-plus#88]
Could you please add a couple of features:
1 The ability to modify some of parameters at runtime?
2 The ability to combine a power of workstations by receiving incoming connections? (yes, it's about local pool)
Thank you

**Comment by exploitagency** [comment]
1) Try ./vanitygen --help
2) You can host a server locally with your own getWork URL and run oclvanityminer and when the solution is found and submitted by oclvanityminer to the server then it can be deleted by your "pool" from the getWork URL.  You should be able to script this fairly easily since there is no need to actually distribute the rewards.  The only inconvenience is that once a solution is found you have to use keyconv to combine the split key, which to me seems more like a security feature.  Or just run multiple instances of vanitygen, there is no "progress", it just searches randomly.
